name: Nextjs CI

on:
  push:
    branches: ["prod", "dev"]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build and run
        run: |
          npm install 
          npm run build
          pm2 restart app-name-dev || pm2 start npm --name "app-name-dev" -- start
